server:
  port: 8081
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  web:
    upload-path: F:/file/
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${spring.web.upload-path}
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/test??characterEncoding\=utf8&zeroDateTimeBehavior\=convertToNull
    username: root
    password: root
    databasename: teaching_platform
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  servlet:
    multipart:
      max-file-size: 10Mb
##  dubbo:
##     application:
##       name: consumer
##     registry:
##       address: zookeeper://192.168.1.128:2181
##     scan: cn.cqupt.teachresource
logging:
  level:
    cn:
      cqupt:
        teachresource:
          mapper: debug
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.cqupt.model
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
